// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcComponentsApi.Data;

#nullable disable

namespace PcComponentsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525201010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PcComponentsApi.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            Description = "8-core gaming processor",
                            ManufacturerId = 1,
                            Name = "Ryzen 7 7800X3D",
                            TypeId = 1
                        },
                        new
                        {
                            Code = "GPU0000001",
                            Description = "High-end gaming graphics card",
                            ManufacturerId = 2,
                            Name = "RTX 4080 Super",
                            TypeId = 2
                        },
                        new
                        {
                            Code = "RAM0000001",
                            Description = "DDR5 RAM module 16GB",
                            ManufacturerId = 3,
                            Name = "Corsair Vengeance DDR5 16GB",
                            TypeId = 3
                        });
                });

            modelBuilder.Entity("PcComponentsApi.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NV",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "COR",
                            FoundationDate = new DateOnly(1994, 1, 1),
                            FullName = "Corsair Gaming Inc."
                        });
                });

            modelBuilder.Entity("PcComponentsApi.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("PcComponentsApi.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warranty")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creator Station",
                            Stock = 3,
                            Warranty = 36,
                            Weight = 9.8000000000000007
                        });
                });

            modelBuilder.Entity("PcComponentsApi.Models.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "RAM0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        });
                });

            modelBuilder.Entity("PcComponentsApi.Models.Component", b =>
                {
                    b.HasOne("PcComponentsApi.Models.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcComponentsApi.Models.ComponentType", "Type")
                        .WithMany("Components")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PcComponentsApi.Models.PcComponent", b =>
                {
                    b.HasOne("PcComponentsApi.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcComponentsApi.Models.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("PcComponentsApi.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("PcComponentsApi.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PcComponentsApi.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PcComponentsApi.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
